c_compiler:            # [win]
  - vs2019             # [win]
cxx_compiler:          # [win]
  - vs2019             # [win]
c_compiler_version:    # [osx]
  - 18                 # [osx]
cxx_compiler_version:  # [osx]
  - 18                 # [osx]
